#!/bin/sh

set -e


case "$1" in
    configure)
        # create a [[artifactId]] group and user
        if ! getent passwd [[artifactId]] >/dev/null 2>&1; then
                addgroup --system --gid 257 [[artifactId]]
                adduser --system --uid 257 --gid 257 [[artifactId]]
        fi
        
        mkdir -p /var/log/SBB/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /var/log/SBB/[[artifactId]]
        mkdir -p /etc/SBB/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /etc/SBB/[[artifactId]]
        mkdir -p /usr/local/SBB/usr/local/[[artifactId]] && chown -R [[artifactId]]:[[artifactId]] /usr/local/SBB/usr/local/[[artifactId]]
    ;;


    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Start [[artifactId]]

update-rc.d [[artifactId]] defaults 85
service [[artifactId]] stop >/dev/null 2>&1 || true
service [[artifactId]] start || true

exit 0

