---
eureka:
  client:
    enabled: false
    service-url:
      registerWithEureka: false

spring:
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

hsp:
  highlight:
    snippetCount: 3
  facets:
    - format-facet
    - has-notation-facet
    - illuminated-facet
    - language-facet
    - material-facet
    - object-type-facet
    - orig-date-type-facet
    - orig-place-facet
    - repository-facet
    - settlement-facet
    - type-facet
  fields:
    - accompanying-material-search
    - accompanying-material-search-exact
    - accompanying-material-search-exact-no-punctuation
    - accompanying-material-search-stemmed
    - author-search
    - author-search-search-exact
    - author-search-exact-no-punctuation
    - binding-search
    - binding-search-exact
    - binding-search-exact-no-punctuation
    - binding-search-stemmed
    - binding-orig-place-search
    - binding-orig-place-search-exact
    - binding-orig-place-search-exact-no-punctuation
    - binding-orig-place-search-stemmed
    - booklet-search
    - booklet-search-exact
    - booklet-search-exact-no-punctuation
    - booklet-search-stemmed
    - collection-search
    - collection-search-exact
    - collection-search-exact-no-punctuation
    - collection-search-stemmed
    - colophon-search
    - colophon-search-exact
    - colophon-search-exact-no-punctuation
    - colophon-search-stemmed
    - decoration-search
    - decoration-search-exact
    - decoration-search-exact-no-punctuation
    - decoration-search-stemmed
    - editor-search
    - editor-search-exact
    - editor-search-exact-no-punctuation
    - explicit-search
    - explicit-search-exact
    - explicit-search-exact-no-punctuation
    - explicit-search-stemmed
    - format-search^10
    - fragment-search
    - fragment-search-exact^10
    - fragment-search-exact-no-punctuation^10
    - fragment-search-stemmed
    - fulltext-search
    - fulltext-search-exact
    - fulltext-search-exact-no-punctuation
    - fulltext-search-stemmed
    - group-id-search
    - has-notation-search
    - height-search
    - history-search
    - history-search-exact
    - history-search-exact-no-punctuation
    - history-search-stemmed
    - id-search^10
    - id-search-exact^10
    - idno-search^1000
    - idno-search-exact^1000
    - idno-search-exact-no-punctuation^1000
    - idno-alternative-search^500
    - idno-alternative-search-exact^500
    - idno-alternative-search-exact-no-punctuation^500
    - illuminated-search
    - incipit-search
    - incipit-search-exact
    - incipit-search-exact-no-punctuation
    - incipit-search-stemmed
    - initium-search
    - initium-search-exact
    - initium-search-exact-no-punctuation
    - initium-search-stemmed
    - institution-mentioned-search
    - institution-mentioned-search-exact
    - institution-mentioned-search-exact-no-punctuation
    - institution-mentioned-search-stemmed
    - institution-producing-search
    - institution-producing-search-exact
    - institution-producing-search-exact-no-punctuation
    - institution-producing-search-stemmed
    - institution-previously-owning-search
    - institution-previously-owning-search-exact
    - institution-previously-owning-search-exact-no-punctuation
    - institution-previously-owning-search-stemmed
    - item-iconography-search
    - item-iconography-search-exact
    - item-iconography-search-exact-no-punctuation
    - item-iconography-search-stemmed
    - item-music-search
    - item-music-search-exact
    - item-music-search-exact-no-punctuation
    - item-music-search-stemmed
    - item-text-search
    - item-text-search-exact
    - item-text-search-exact-no-punctuation
    - item-text-search-stemmed
    - language-search^10
    - language-search-exact^10
    - language-search-exact-no-punctuation^10
    - language-search-stemmed^5
    - leaves-count-search
    - material-search^10
    - material-search-exact^10
    - material-search-exact-no-punctuation^10
    - material-search-stemmed^5
    - ms-identifier-search^1000
    - ms-identifier-search-exact^1000
    - ms-identifier-search-exact-no-punctuation^1000
    - object-type-search^10
    - orig-date-type-search
    - orig-date-from-search
    - orig-date-to-search
    - orig-date-when-search
    - orig-date-when-search-exact
    - orig-date-when-search-exact-no-punctuation
    - orig-date-when-search-stemmed
    - orig-place-search^100
    - orig-place-search-exact^100
    - orig-place-search-exact-no-punctuation^100
    - orig-place-search-stemmed^20
    - person-author-search
    - person-author-search-exact
    - person-author-search-exact-no-punctuation
    - person-bookbinder-search
    - person-bookbinder-search-exact
    - person-bookbinder-search-exact-no-punctuation
    - person-commissioned-by-search
    - person-commissioned-by-search-exact
    - person-commissioned-by-search-exact-no-punctuation
    - person-conservator-search
    - person-conservator-search-exact
    - person-conservator-search-exact-no-punctuation
    - person-illuminator-search
    - person-illuminator-search-exact
    - person-illuminator-search-exact-no-punctuation
    - person-mentioned-in-search
    - person-mentioned-in-search-exact
    - person-mentioned-in-search-exact-no-punctuation
    - person-other-search
    - person-other-search-exact
    - person-other-search-exact-no-punctuation
    - person-previous-owner-search
    - person-previous-owner-search-exact
    - person-previous-owner-search-exact-no-punctuation
    - person-scribe-search
    - person-scribe-search-exact
    - person-scribe-search-exact-no-punctuation
    - person-translator-search
    - person-translator-search-exact
    - person-translator-search-exact-no-punctuation
    - physical-description-search
    - physical-description-search-exact
    - physical-description-search-exact-no-punctuation
    - physical-description-search-stemmed
    - publish-year-search
    - publisher-search
    - publisher-search-exact
    - publisher-search-exact-no-punctuation
    - quotation-search
    - quotation-search-exact
    - quotation-search-exact-no-punctuation
    - quotation-search-stemmed
    - repository-search^100
    - repository-search-exact^100
    - repository-search-exact-no-punctuation^100
    - repository-search-stemmed^20
    - settlement-search^100
    - settlement-search-exact^100
    - settlement-search-exact-no-punctuation^100
    - settlement-search-stemmed^20
    - status-search^10
    - title-search^200
    - title-search-exact^200
    - title-search-exact-no-punctuation^200
    - title-search-stemmed^100
    - title-in-ms-search^200
    - title-in-ms-search-exact^200
    - title-in-ms-search-exact-no-punctuation^200
    - title-in-ms-search-stemmed^100
    - width-search
    - work-title-search
    - work-title-search-exact
    - work-title-search-exact-no-punctuation
    - work-title-search-stemmed
  # group field names MUST not be boosted, as the field's default boosting (hsp.fields) is used
  groups:
    FIELD-GROUP-ALL:
      - author-search
      - accompanying-material-search
      - binding-search
      - binding-orig-place-search
      - booklet-search
      - collection-search
      - colophon-search
      - decoration-search
      - described-object-search
      - digitized-iiif-object-search
      - digitized-object-search
      - editor-search
      - explicit-search
      - format-search
      - fragment-search
      - fulltext-search
      - has-notation-facet
      - height-search
      - history-search
      - id-search
      - idno-search
      - idno-alternative-search
      - illuminated-search
      - incipit-search
      - initium-search
      - institution-mentioned-search
      - institution-producing-search
      - institution-previously-owning-search
      - item-iconography-search
      - item-music-search
      - item-text-search
      - language-search
      - leaves-count-search
      - material-search
      - ms-identifier-search
      - object-type-search
      - orig-date-type-search
      - orig-date-when-search
      - orig-place-search
      - person-author-search
      - person-bookbinder-search
      - person-commissioned-by-search
      - person-conservator-search
      - person-illuminator-search
      - person-mentioned-in-search
      - person-other-search
      - person-previous-owner-search
      - person-scribe-search
      - person-translator-search
      - physical-description-search
      - quotation-search
      - repository-search
      - settlement-search
      - status-search
      - title-search
      - title-in-ms-search
      - width-search
      - work-title-search
    FIELD-GROUP-BASIC:
      - format-search
      - idno-search
      - language-search
      - material-search
      - object-type-search
      - orig-place-search
      - repository-search
      - settlement-search
      - status-search
      - title-search
    FIELD-GROUP-INCIPIT:
      - initium-search
    FIELD-GROUP-ORIGIN:
      - binding-orig-place-search
      - orig-place-search
    FIELD-GROUP-QUOTE:
      - colophon-search
      - explicit-search
      - incipit-search
      - initium-search
      - quotation-search
    FIELD-GROUP-PERSON:
      - person-author-search
      - person-bookbinder-search
      - person-commissioned-by-search
      - person-conservator-search
      - person-illuminator-search
      - person-mentioned-in-search
      - person-other-search
      - person-previous-owner-search
      - person-scribe-search
      - person-translator-search
    FIELD-GROUP-SIGNATURE:
      - collection-search
      - idno-search
      - idno-alternative-search
      - ms-identifier-search
      - repository-search
      - settlement-search
    FIELD-GROUP-TITLE:
      - title-search
      - title-in-ms-search
      - work-title-search
  stats:
    - height-facet
    - leaves-count-facet
    - orig-date-from-facet
    - orig-date-to-facet
    - orig-date-when-facet
    - width-facet

info:
  component: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'

logging:
  config: classpath:logback-test.xml

solr:
  core: hsp
  host: http://b-dev1054.pk.de:8983